version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: octrow/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: octrow/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: octrow/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    ports:
      - 9000:80
